"""initial_schema

Revision ID: 028b2e3d7683
Revises: 
Create Date: 2026-09-26 17:53:12.865385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_sessions_token_hash'), ['token_hash'], unique=True)

    op.create_table('admin_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('ai_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('groq', 'openrouter', name='ai_provider_type', native_enum=False), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=True),
    sa.Column('quota_group', sa.String(length=64), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False),
    sa.Column('key_hint', sa.String(length=32), nullable=False),
    sa.Column('key_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_credentials_key_fingerprint'), ['key_fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_ai_credentials_provider'), ['provider'], unique=False)

    op.create_table('ai_provider_runtime',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('quota_group', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ok', 'cooldown', 'exhausted', name='ai_provider_status', native_enum=False), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('consecutive_errors', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'quota_group', name='uq_provider_quota_group')
    )
    op.create_table('browser_installations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('browser_installations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_browser_installations_token_hash'), ['token_hash'], unique=True)

    op.create_table('startup_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('startup_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_startup_templates_slug'), ['slug'], unique=True)

    op.create_table('ai_key_tests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'passed', 'failed', 'cancelled', name='key_test_status', native_enum=False), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['ai_credentials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_key_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_key_tests_credential_id'), ['credential_id'], unique=False)

    op.create_table('startup_template_versions',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=False),
    sa.Column('public_profile', sa.JSON(), nullable=False),
    sa.Column('private_profile', sa.JSON(), nullable=False),
    sa.Column('finance_config', sa.JSON(), nullable=False),
    sa.Column('asset_key', sa.String(length=80), nullable=False),
    sa.Column('baseline_series', sa.JSON(), nullable=False),
    sa.Column('baseline_cash_m9_kopeks', sa.BigInteger(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['startup_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id', 'version')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('browser_installation_id', sa.Uuid(), nullable=False),
    sa.Column('startup_template_id', sa.Uuid(), nullable=False),
    sa.Column('startup_version', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=24), nullable=False),
    sa.Column('status', sa.Enum('ready', 'processing', 'result_pending', 'completed', name='session_status', native_enum=False), nullable=False),
    sa.Column('next_round', sa.SmallInteger(), nullable=False),
    sa.Column('elapsed_months', sa.SmallInteger(), nullable=False),
    sa.Column('template_snapshot', sa.JSON(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('scoring_version', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('ranking_eligible', sa.Boolean(), nullable=False),
    sa.Column('final_status', sa.Enum('survived', 'deep_crisis', 'near_bankruptcy', 'bankrupt', name='final_status', native_enum=False), nullable=True),
    sa.Column('final_score', sa.SmallInteger(), nullable=True),
    sa.Column('bankruptcy_month', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['browser_installation_id'], ['browser_installations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_template_id', 'startup_version'], ['startup_template_versions.template_id', 'startup_template_versions.version'], name='fk_game_sessions_startup_template_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_sessions_browser_installation_id'), ['browser_installation_id'], unique=True)
        batch_op.create_index('ix_game_sessions_leaderboard', ['final_score', 'completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_sessions_status'), ['status'], unique=False)
        batch_op.create_index('ix_game_sessions_status_score', ['status', 'final_score'], unique=False)

    op.create_table('game_rounds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('round_number', sa.SmallInteger(), nullable=False),
    sa.Column('idempotency_key', sa.Uuid(), nullable=False),
    sa.Column('request_sha256', sa.String(length=64), nullable=False),
    sa.Column('attack_text', sa.String(length=500), nullable=False),
    sa.Column('hint_id', sa.String(length=48), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'resolved', name='round_status', native_enum=False), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.JSON(), nullable=True),
    sa.Column('event_title', sa.String(length=120), nullable=True),
    sa.Column('event_narrative', sa.Text(), nullable=True),
    sa.Column('defense_summary', sa.Text(), nullable=True),
    sa.Column('new_circumstance', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'idempotency_key', name='uq_game_rounds_session_idempotency'),
    sa.UniqueConstraint('session_id', 'round_number', name='uq_game_rounds_session_round')
    )
    with op.batch_alter_table('game_rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_rounds_session_id'), ['session_id'], unique=False)

    op.create_table('ai_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'retry_wait', 'waiting_for_provider', 'completed', 'fallback_completed', name='job_status', native_enum=False), nullable=False),
    sa.Column('primary_model', sa.String(length=80), nullable=False),
    sa.Column('model_used', sa.String(length=80), nullable=True),
    sa.Column('attempt_count', sa.SmallInteger(), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('credential_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('quota_group', sa.String(length=64), nullable=True),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('provider_request_id', sa.String(length=128), nullable=True),
    sa.Column('usage', sa.JSON(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['game_rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_ai_jobs_poll', ['status', 'available_at', 'lease_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_jobs_round_id'), ['round_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ai_jobs_status'), ['status'], unique=False)

    op.create_table('ai_usage_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('round_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('requested_model', sa.String(length=80), nullable=False),
    sa.Column('actual_model_id', sa.String(length=128), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['ai_credentials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['round_id'], ['game_rounds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_events_credential_id'), ['credential_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_events_round_id'), ['round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_events_session_id'), ['session_id'], unique=False)

    op.create_table('monthly_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('month_no', sa.SmallInteger(), nullable=False),
    sa.Column('opening_cash_kopeks', sa.BigInteger(), nullable=False),
    sa.Column('revenue_by_stream', sa.JSON(), nullable=False),
    sa.Column('variable_cost_kopeks', sa.BigInteger(), nullable=False),
    sa.Column('fixed_cost_kopeks', sa.BigInteger(), nullable=False),
    sa.Column('incident_cost_kopeks', sa.BigInteger(), nullable=False),
    sa.Column('defense_cost_kopeks', sa.BigInteger(), nullable=False),
    sa.Column('closing_cash_kopeks', sa.BigInteger(), nullable=False),
    sa.Column('unpaid_obligations_kopeks', sa.BigInteger(), nullable=False),
    sa.Column('reputation_after', sa.SmallInteger(), nullable=False),
    sa.Column('applied_effects', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['game_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'month_no', name='uq_monthly_ledger_session_month')
    )
    with op.batch_alter_table('monthly_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_ledger_round_id'), ['round_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_ledger_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_ledger_session_id'))
        batch_op.drop_index(batch_op.f('ix_monthly_ledger_round_id'))

    op.drop_table('monthly_ledger')
    with op.batch_alter_table('ai_usage_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_events_round_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_events_credential_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_events_created_at'))

    op.drop_table('ai_usage_events')
    with op.batch_alter_table('ai_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_ai_jobs_round_id'))
        batch_op.drop_index('ix_ai_jobs_poll')

    op.drop_table('ai_jobs')
    with op.batch_alter_table('game_rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_rounds_session_id'))

    op.drop_table('game_rounds')
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_game_sessions_status_score')
        batch_op.drop_index(batch_op.f('ix_game_sessions_status'))
        batch_op.drop_index('ix_game_sessions_leaderboard')
        batch_op.drop_index(batch_op.f('ix_game_sessions_browser_installation_id'))

    op.drop_table('game_sessions')
    op.drop_table('startup_template_versions')
    with op.batch_alter_table('ai_key_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_key_tests_credential_id'))

    op.drop_table('ai_key_tests')
    with op.batch_alter_table('startup_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_startup_templates_slug'))

    op.drop_table('startup_templates')
    with op.batch_alter_table('browser_installations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_browser_installations_token_hash'))

    op.drop_table('browser_installations')
    op.drop_table('ai_provider_runtime')
    with op.batch_alter_table('ai_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_credentials_provider'))
        batch_op.drop_index(batch_op.f('ix_ai_credentials_key_fingerprint'))

    op.drop_table('ai_credentials')
    op.drop_table('admin_settings')
    with op.batch_alter_table('admin_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_admin_sessions_expires_at'))

    op.drop_table('admin_sessions')
    # ### end Alembic commands ###
